# Generated by Django 3.2.5 on 2021-07-02 15:22

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='quantity',
            new_name='amount',
        ),
        migrations.RenameField(
            model_name='sale',
            old_name='quantity_sold',
            new_name='amount_sold',
        ),
        migrations.RemoveField(
            model_name='product',
            name='seller',
        ),
        migrations.AddField(
            model_name='product',
            name='sellers',
            field=models.ManyToManyField(to='shop.Seller'),
        ),
    ]
