# Generated by Django 3.2.5 on 2021-07-03 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_auto_20210702_1822'),
    ]

    operations = [
        migrations.AddField(
            model_name='sale',
            name='purchase_amount',
            field=models.PositiveIntegerField(default=100),
            preserve_default=False,
        ),
    ]
